"""
generate_material.py
====================
Builds MATERIAL_16MnCr5.inp - a phase-dependent THERMAL material card for the
Abaqus built-in phase-transformation framework (ABQ_PHASE_TRANS tables),
using ONLY public, reproducible sources:

  * Thermal properties of BCC phases (ferrite / bainite / martensite):
      EN 1993-1-2:2005, sec. 3.4 - carbon steel (k, cp, rho).
  * Thermal properties of the FCC phase (austenite):
      EN 1993-1-2:2005, Annex C - austenitic stainless steel (k, cp),
      used as a proxy for austenite.
  * Critical temperatures from the nominal EN 10084 composition with
    classical empirical formulae:
      Ac1, Ac3, Ms : K.W. Andrews, JISI 203 (1965) 721-727
      Bs           : W. Steven & A.G. Haynes, JISI 183 (1956) 349-359
  * Martensite kinetics: Koistinen & Marburger, Acta Metall. 7 (1959) 59.
  * Diffusional kinetics (TTT start/end times): ILLUSTRATIVE C-curves only.
    JMA coefficients are derived from them consistently:
        X = 1 - exp(-k t^n),  X(ts) = 0.05,  X(te) = 0.95
        n = ln( ln(0.05)/ln(0.95) ) / ln(te/ts),   k = -ln(0.95) / ts^n
    -> replace with calibrated CCT/TTT data before any quantitative use.

Only the thermal problem is modelled, so no elastic/plastic/expansion data
are included.

Usage:  python generate_material.py [output.inp]
"""
import math
import sys

# ---------------------------------------------------------------------------
# Nominal composition, EN 10084 16MnCr5 (wt-%, mid-range)
# ---------------------------------------------------------------------------
C, SI, MN, CR, NI, MO, V = 0.16, 0.25, 1.15, 0.95, 0.0, 0.0, 0.0

AC1 = 723 - 10.7 * MN - 16.9 * NI + 29.1 * SI + 16.9 * CR          # Andrews
AC3 = 910 - 203 * math.sqrt(C) - 15.2 * NI + 44.7 * SI + 104 * V + 31.5 * MO
MS = 539 - 423 * C - 30.4 * MN - 17.7 * NI - 12.1 * CR - 7.5 * MO   # Andrews
BS = 830 - 270 * C - 90 * MN - 37 * NI - 70 * CR - 83 * MO          # Steven-Haynes
KM = 0.011                                                         # K-M
AC1, AC3, MS, BS = (round(x) for x in (AC1, AC3, MS, BS))

# Melting range and latent heat: typical values for low-alloy steels
T_SOL, T_LIQ = 1490.0, 1515.0
LATENT = 270.0e3            # J/kg
RHO = 7850.0                # kg/m3, EN 1993-1-2 sec. 3.2.2

# Unit conversion to mm-t-s-mJ: k [W/mK]=[mW/mmK]; cp [J/kgK]*1e6=[mJ/tK]
CP_SCALE = 1.0e6


# ---------------------------------------------------------------------------
# EN 1993-1-2 carbon steel (BCC phases)
# ---------------------------------------------------------------------------
def k_carbon(T):
    return 54.0 - 3.33e-2 * T if T < 800 else 27.3


def cp_carbon(T):
    if T < 600:
        return 425 + 7.73e-1 * T - 1.69e-3 * T**2 + 2.22e-6 * T**3
    if T < 735:
        return 666 + 13002.0 / (738 - T)
    if T < 900:
        return 545 + 17820.0 / (T - 731)
    return 650.0


# ---------------------------------------------------------------------------
# EN 1993-1-2 Annex C stainless steel (proxy for austenite)
# ---------------------------------------------------------------------------
def k_aust(T):
    return 14.6 + 1.27e-2 * T


def cp_aust(T):
    return 450 + 0.280 * T - 2.91e-4 * T**2 + 1.34e-7 * T**3


T_BCC_K = [20, 100, 200, 300, 400, 500, 600, 700, 800, 1200, 1600]
T_BCC_CP = [20, 100, 200, 300, 400, 500, 600, 650, 700, 720, 730, 735,
            740, 750, 775, 800, 850, 900, 1200, 1600]
T_FCC = [20, 200, 400, 600, 800, 1000, 1200, 1400, 1600]

# phase-fraction tags: (fAustenite, fBainite, fMartensite); ferrite = all 0
PHASES = [("Ferrite", (0, 0, 0), "bcc"), ("Austenite", (1, 0, 0), "fcc"),
          ("Bainite", (0, 1, 0), "bcc"), ("Martensite", (0, 0, 1), "bcc")]


def jma(ts, te, x0=0.05, x1=0.95):
    n = math.log(math.log(1 - x0) / math.log(1 - x1)) / math.log(te / ts)
    k = -math.log(1 - x0) / ts**n
    return k, n


# Illustrative TTT C-curves (start time ts [s], te/ts ratio, T [C])
TTT_A_TO_F = [(BS + 5, 6.0), (650, 3.0), (680, 4.5), (710, 10.0),
              (AC1 + 6, 40.0), (780, 150.0)]
RATIO_F = 8.0
TTT_A_TO_B = [(MS, 1.2), (450, 0.9), (500, 1.5), (550, 4.0), (BS - 7, 15.0)]
RATIO_B = 15.0
# Heating (austenitisation): fast kinetics increasing with superheat
TTT_HEAT = [(AC1, 1.0, 10.0), (AC1 + 30, 0.1, 1.0), (AC3, 1.0e-2, 0.1),
            (AC3 + 100, 1.0e-3, 1.0e-2), (T_SOL, 1.0e-6, 1.0e-5)]


def main(out="MATERIAL_16MnCr5.inp"):
    L = []
    w = L.append
    w("** " + "=" * 70)
    w("** 16MnCr5 (EN 10084) - phase-dependent THERMAL material card")
    w("** Generated by generate_material.py from PUBLIC sources (see header")
    w("** of the script). Diffusional kinetics are ILLUSTRATIVE ONLY.")
    w("** Units: mm, s, tonne, mJ, C")
    w(f"** Composition: C={C} Si={SI} Mn={MN} Cr={CR} Ni={NI} Mo={MO}")
    w(f"** Ac1={AC1} Ac3={AC3} Bs={BS} Ms={MS} C (empirical formulae)")
    w("** " + "=" * 70)
    w('*MATERIAL, NAME="ABQ_PHASE_TRANS_16MNCR5"')
    w("*DENSITY")
    w(f" {RHO*1e-12:.4E},")
    w("**")
    w("*CONDUCTIVITY, TYPE=ISOTROPIC, DEPENDENCIES=3")
    w("** k (mW/mm/K), Temp (C), fAustenite, fBainite, fMartensite")
    for name, tag, lat in PHASES:
        w(f"** {name}: " + ("EN 1993-1-2 Annex C" if lat == "fcc"
                            else "EN 1993-1-2 sec. 3.4.1.3"))
        for T in (T_FCC if lat == "fcc" else T_BCC_K):
            k = k_aust(T) if lat == "fcc" else k_carbon(T)
            w(f" {k:7.3f}, {T:7.1f}, {tag[0]}., {tag[1]}., {tag[2]}.")
    w("**")
    w("*SPECIFIC HEAT, DEPENDENCIES=3")
    w("** cp (mJ/tonne/K), Temp (C), fAustenite, fBainite, fMartensite")
    for name, tag, lat in PHASES:
        w(f"** {name}: " + ("EN 1993-1-2 Annex C" if lat == "fcc"
                            else "EN 1993-1-2 sec. 3.4.1.2"))
        for T in (T_FCC if lat == "fcc" else T_BCC_CP):
            cp = cp_aust(T) if lat == "fcc" else cp_carbon(T)
            w(f" {cp*CP_SCALE:.4E}, {T:7.1f}, {tag[0]}., {tag[1]}., {tag[2]}.")
    w("**")
    w("*USER DEFINED FIELD, TYPE=USER")
    w("*DEPVAR")
    w("** 3 (RLS, fGrainColumnar, GrainSize) + 4 phases + 3 x 6 transformations")
    w("25")
    for i, n in enumerate(["RLS", "fGrainColumnar", "GrainSize",
                           "fPhase_Ferrite", "fPhase_Austenite",
                           "fPhase_Bainite", "fPhase_Martensite"], 1):
        w(f"{i}, {n}")
    w('*PARAMETER TABLE, TYPE="ABQ_PHASE_TRANS_MeltingTemperature"')
    w(f"{T_SOL:g}, {T_LIQ:g},")
    w("*LATENT HEAT")
    w(f"{LATENT*CP_SCALE:.3E}, {T_SOL:g}, {T_LIQ:g}, 1.0")
    w("** Anneal temperature: only used by a sequential mechanical analysis")
    w("*ANNEAL TEMPERATURE")
    w(f"{T_LIQ:g},")
    w('*PARAMETER TABLE, TYPE="ABQ_PHASE_TRANS_SolidPhases"')
    w('"Ferrite", 0.,')
    w('"Austenite", 1.,')
    w('"Bainite", 0.,')
    w('"Martensite", 0.,')
    w('*PARAMETER TABLE, TYPE="ABQ_PHASE_TRANS_Transformations"')
    w("** --- Cooling transformations ---")
    tr = [("AtoF", "MAX", -1e36, 0.0, "INTERVAL", BS, AC3, "DIFFUSIONAL", "JMA",
           "Austenite", "Ferrite"),
          ("AtoB", "MAX", -1e36, 0.0, "INTERVAL", MS, BS, "DIFFUSIONAL", "JMA",
           "Austenite", "Bainite"),
          ("AtoM", "MAX", -1e36, 0.0, "MAX", -1e36, MS, "MARTENSITIC", "KM",
           "Austenite", "Martensite")]
    for p in ("Ferrite", "Bainite", "Martensite"):
        tr.append((f"{p[0]}toA", "MIN", 0.0, 1e36, "INTERVAL", AC1, T_SOL,
                   "DIFFUSIONAL", "TTT", p, "Austenite"))
    for i, t in enumerate(tr):
        if i == 3:
            w("** --- Heating transformations ---")
        lo = f"{t[2]:g}".replace("e+", "E").replace("e", "E")
        hi = f"{t[3]:g}".replace("e+", "E").replace("e", "E")
        tl = f"{t[5]:g}".replace("e+", "E").replace("e", "E")
        w(f'"{t[0]}", {t[1]}, {lo}, {hi}, {t[4]}, {tl}, {t[6]:g}., {t[7]}, '
          f'{t[8]}, NO, 1, 1, "{t[9]}", " ", " ", "{t[10]}",')
        w('" ", " ",' if i < len(tr) - 1 else '" ", " "')

    def diffusional_cooling(label, curve, ratio, eq_lo, eq_hi):
        w(f"** --- {label} (ILLUSTRATIVE C-curve, te/ts = {ratio:g}) ---")
        w('*PARAMETER TABLE, TYPE="ABQ_PHASE_TRANS_Diffusional_TTT_Constants", '
          f'LABEL="ABQ_PHASE_TRANS_Trans_{label}_TTT_Constants"')
        w(" 0.05, 0.95")
        w('*PROPERTY TABLE, TYPE="ABQ_PHASE_TRANS_Diffusional_TTT_Diagram", '
          f'LABEL="ABQ_PHASE_TRANS_Trans_{label}_TTT_Diagram", TEMPERATURE')
        w("** Start Time, End Time, Temp(C)")
        for T, ts in curve:
            w(f" {ts:g}, {ts*ratio:g}, {T:g}.")
        w('*PROPERTY TABLE, TYPE="ABQ_PHASE_TRANS_Diffusional_JMA_Coefficients", '
          f'LABEL="ABQ_PHASE_TRANS_Trans_{label}_JMA_Coefficients", TEMPERATURE')
        w("** k, n, Temp(C)   [derived from the TTT curve above]")
        for T, ts in curve:
            k, n = jma(ts, ts * ratio)
            w(f" {k:.4E}, {n:.4f}, {T:g}.")
        w('*PROPERTY TABLE, TYPE="ABQ_PHASE_TRANS_Diffusional_ParentEquiFrac", '
          f'LABEL="ABQ_PHASE_TRANS_Trans_{label}_ParentEquiFrac", TEMPERATURE')
        w(f" 0.0, {eq_lo:g}.")
        w(f" 1.0, {eq_hi:g}.")

    diffusional_cooling("AtoF", TTT_A_TO_F, RATIO_F, AC1, AC3)
    diffusional_cooling("AtoB", TTT_A_TO_B, RATIO_B, MS, BS)

    x0, x1 = 0.05, 0.90
    dT0, dT1 = -math.log(1 - x0) / KM, -math.log(1 - x1) / KM
    w(f"** --- AtoM: Koistinen-Marburger, gamma = {KM} 1/K, Ms = {MS} C ---")
    w('*PROPERTY TABLE, TYPE="ABQ_PHASE_TRANS_Martensitic_KM_Coefficients", '
      'LABEL="ABQ_PHASE_TRANS_Trans_AtoM_KM_Coefficients"')
    w(f" {KM}")
    w('*PARAMETER TABLE, TYPE="ABQ_PHASE_TRANS_Martensitic_TTT_Constants", '
      'LABEL="ABQ_PHASE_TRANS_Trans_AtoM_TTT_Constants"')
    w(f" {x0}, {x1}")
    w('*PROPERTY TABLE, TYPE="ABQ_PHASE_TRANS_Martensitic_TTT_Diagram", '
      'LABEL="ABQ_PHASE_TRANS_Trans_AtoM_TTT_Diagram"')
    w(f"** temperatures at {x0:.0%} and {x1:.0%} martensite from K-M")
    w(f" {MS - dT0:.0f}., {MS - dT1:.0f}.")
    w('*PROPERTY TABLE, TYPE="ABQ_PHASE_TRANS_Martensitic_ParentRetainedFrac", '
      'LABEL="ABQ_PHASE_TRANS_Trans_AtoM_ParentRetainedFrac"')
    w("** Retained proportion, Starting proportion  (no retained austenite)")
    w(" 0., 0.")
    w(" 0., 1.")

    for p in ("F", "B", "M"):
        lab = f"{p}toA"
        w(f"** --- {lab}: austenitisation on heating (ILLUSTRATIVE) ---")
        w('*PARAMETER TABLE, TYPE="ABQ_PHASE_TRANS_Diffusional_TTT_Constants", '
          f'LABEL="ABQ_PHASE_TRANS_Trans_{lab}_TTT_Constants"')
        w(" 0.05, 0.95")
        w('*PROPERTY TABLE, TYPE="ABQ_PHASE_TRANS_Diffusional_TTT_Diagram", '
          f'LABEL="ABQ_PHASE_TRANS_Trans_{lab}_TTT_Diagram", TEMPERATURE')
        for T, ts, te in TTT_HEAT:
            w(f" {ts:g}, {te:g}, {T:g}.")
        w('*PROPERTY TABLE, TYPE="ABQ_PHASE_TRANS_Diffusional_ParentEquiFrac", '
          f'LABEL="ABQ_PHASE_TRANS_Trans_{lab}_ParentEquiFrac", TEMPERATURE')
        w(f" 1.0, {AC1:g}.")
        w(f" 0.0, {AC3:g}.")

    w('*PARAMETER TABLE, TYPE="ABQ_PHASE_TRANS_FieldVariables"')
    w('1, "RFPHASE2",')
    w('2, "RFPHASE3",')
    w('3, "RFPHASE4",')
    w("**")
    with open(out, "w") as f:
        f.write("\n".join(L) + "\n")
        f.write(TABLE_TYPES)
    print(f"Written {out}")
    print(f"  Ac1={AC1}  Ac3={AC3}  Bs={BS}  Ms={MS}  "
          f"Ts={T_SOL:g}  Tl={T_LIQ:g}  (C)")


# Table-type declarations required by the ABQ_PHASE_TRANS framework
# (as documented in the Abaqus Analysis User's Guide; case sensitive).
TABLE_TYPES = """\
*********************************************
** Table types and labels are case sensitive
*********************************************
**-------------------------------------------
**RLS state
**-------------------------------------------
*PARAMETER TABLE TYPE,  NAME="ABQ_PHASE_TRANS_MeltingTemperature", parameters=2
 FLOAT, , "Solidus Temperature" , , ,
 FLOAT, , "Liquidus Temperature", , ,
**-------------------------------------------
**Solid-phase Transformations
**-------------------------------------------
*PARAMETER TABLE TYPE,  NAME="ABQ_PHASE_TRANS_SolidPhases", parameters=2
 STRING ,   , "Solid Phase Name"                    , , ,
 FLOAT  ,   , "Initial Fraction upon Solidification", , ,
**
*PARAMETER TABLE TYPE, NAME="ABQ_PHASE_TRANS_Transformations", parameters=18
 STRING ,      , "Solid-Phase Transformation Name"     , ,                        ,
 STRING ,      , "Temperature Rate Condition"          , , INTERVAL|MIN|MAX|NONE  ,
 FLOAT  , -1E36, "Lower Bound (Temperature Rate Range)", ,                        ,
 FLOAT  ,  1E36, "Upper Bound (Temperature Rate Range)", ,                        ,
 STRING ,      , "Temperature Condition"               , , INTERVAL|MIN|MAX|NONE  ,
 FLOAT  , -1E36, "Lower Bound (Temperature Range)"     , ,                        ,
 FLOAT  ,  1E36, "Upper Bound (Temperature Range)"     , ,                        ,
 STRING ,      , "Transformation Type"                 , , DIFFUSIONAL|MARTENSITIC,
 STRING ,      , "Input Option"                        , , TTT|JMA|KM             ,
 STRING ,      , "Reversible Transformation"           , , NO|YES                 ,
 INTEGER,      , "Parent Phases"                       , ,                        ,
 INTEGER,      , "Child Phases"                        , ,                        ,
 STRING , " "  , "Parent Solid Phase 1 Name"           , ,                        ,
 STRING , " "  , "Parent Solid Phase 2 Name"           , ,                        ,
 STRING , " "  , "Parent Solid Phase 3 Name"           , ,                        ,
 STRING , " "  , "Child Solid Phase 1 Name"            , ,                        ,
 STRING , " "  , "Child Solid Phase 2 Name"            , ,                        ,
 STRING , " "  , "Child Solid Phase 3 Name"            , ,                        ,
**
*PROPERTY TABLE TYPE, NAME="ABQ_PHASE_TRANS_Martensitic_KM_Coefficients", properties=1
 "KM Coefficient gamma"
*PARAMETER TABLE TYPE, NAME="ABQ_PHASE_TRANS_Martensitic_TTT_Constants", parameters=2
 FLOAT, , "Starting Proportion", , ,
 FLOAT, , "Ending Proportion"  , , ,
*PROPERTY TABLE TYPE,  NAME="ABQ_PHASE_TRANS_Martensitic_TTT_Diagram", properties=2
 "Start Temperature"
 "End Temperature"
*PROPERTY TABLE TYPE,  NAME="ABQ_PHASE_TRANS_Martensitic_ParentRetainedFrac", properties=1, independent variables=1
 "Retained Proportion"
 "Starting Proportion"
**
*PROPERTY TABLE TYPE,  NAME="ABQ_PHASE_TRANS_Diffusional_JMA_Coefficients", properties=2
 "JMA Coefficient k"
 "JMA Coefficient n"
*PARAMETER TABLE TYPE, NAME="ABQ_PHASE_TRANS_Diffusional_TTT_Constants", parameters=2
 FLOAT, , "Starting Proportion", , ,
 FLOAT, , "Ending Proportion"  , , ,
*PROPERTY TABLE TYPE, NAME="ABQ_PHASE_TRANS_Diffusional_TTT_Diagram", properties=2
 "Start Time"
 "End Time"
*PROPERTY TABLE TYPE, NAME="ABQ_PHASE_TRANS_Diffusional_ParentEquiFrac", properties=1
 "Parent Equilibrium Proportion"
**-------------------------------------------
**Morphology
**-------------------------------------------
*PARAMETER TABLE TYPE, NAME="ABQ_PHASE_TRANS_SolidificationMap_Constants", parameters=2
 FLOAT, , "Critical Solidification Rate"       , , ,
 FLOAT, , "Constant Grain Size LogR-LogG Slope", , ,
*PROPERTY TABLE TYPE, NAME="ABQ_PHASE_TRANS_SolidificationMap_Diagram", properties=1, independent variables=1
 "LogG"
 "LogR"
**-------------------------------------------
**Grain size
**-------------------------------------------
*PARAMETER TABLE TYPE,  name="ABQ_PHASE_TRANS_GrainSize_Definitions", parameters=4
 FLOAT  ,      , "Initial Grain Size"                          , ,                      ,
 STRING ,      , "Grain-Growth Temperature Condition"          , , INTERVAL|MIN|MAX|NONE,
 FLOAT  , -1E36, "Lower Bound (Grain-Growth Temperature Range)", ,                      ,
 FLOAT  ,  1E36, "Upper Bound (Grain-Growth Temperature Range)", ,                      ,
*PROPERTY TABLE TYPE, NAME="ABQ_PHASE_TRANS_GrainSize_Coefficients", properties=3
 "Grain-Growth Coefficient k"
 "Grain-Growth Coefficient n"
 "Grain-Growth Coefficient Q"
**-------------------------------------------
**Field Variables
**-------------------------------------------
*PARAMETER TABLE TYPE, name="ABQ_PHASE_TRANS_FieldVariables", parameters = 2
 INTEGER, , "Field Variable Index", ,                                      ,
 STRING , , "Data Option"         , , RLS|RFPHASEi|GRAINSIZE|FGRAINCOLUMNAR,
"""

if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "MATERIAL_16MnCr5.inp")
